- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com
    - name: Add mongo repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2
    - name: Install mongo
      apt:
        name: mongodb-org
        state: present
    - name: Enable mongod service
      service:
        name: mongod
        enabled: yes
